blog/urls.py
from django.urls import path
from .views import (
    PostListView,
    PostDetailView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    search
)
from . import views

urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('media/Files/<int:pk>',PostDeleteView.as_view(),name='post-delete' ),
    path('search/', search.as_view(),name='search' ),
    
]

django_web_app/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
import os

class Post(models.Model):
	title = models.CharField(max_length=100)
	file = models.FileField(null=True,blank=True,upload_to='Files')
	content = models.TextField()
	date_posted = models.DateTimeField(default=timezone.now)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	
	def __str__(self):
		return self.title

	def extension(self):
		name, extension = os.path.splitext(self.file.name)
		return extension.lower()

	def get_absolute_url(self):
		return reverse('post-detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image
from django.dispatch import receiver
from django.db.models.signals import post_save
from blog.models import Post

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(label='Email')

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        # Remove help text for username, email, password1, and password2
        for field_name in ['username', 'email', 'password1', 'password2']:
            self.fields[field_name].help_text = None


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']
    
    def __init__(self, *args, **kwargs):
        super(UserUpdateForm, self).__init__(*args, **kwargs)
        # Remove help text for the 'username' and 'email' fields
        for field_name in ['username', 'email']:
            self.fields[field_name].help_text = None


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

blog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Post
from django.contrib.staticfiles.views import serve
from django.db.models import Q



class search(ListView):
    model = Post
    template_name = 'blog/home.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 3

    def get_queryset(self):
        queryset = super().get_queryset()
        query = self.request.GET.get('q')

        if query:
            queryset = queryset.filter(Q(title__icontains=query) | Q(author__username__icontains=query) | Q(content__icontains=query))
        return queryset
   



def getfile(request):
   return serve(request, 'File')




class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html'  
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 3




class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')




class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/post_detail.html'




class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'blog/post_form.html'
    fields = ['title', 'content', 'file']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)




class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    template_name = 'blog/post_form.html'
    fields = ['title', 'content', 'file']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False




class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'
    template_name = 'blog/post_confirm_delete.html'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You are now able to log in')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            return redirect('profile')
        
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form
    }

    return render(request, 'users/profile.html', context)

blog/templates/blog/home.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="shortcut icon" href="{% static 'icon.png' %}" type="image/x-icon">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >
    <link rel="stylesheet" href="{% static 'blog/main.css' %}">

    {% if title %}
        <title>File Hub - {{title}}</title>
    {% else %}
        <title>File Hub</title>
    {% endif %}

    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark">
      <a class="navbar-brand font-weight-bold" href="{% url 'blog-home' %}"><i class="fas fa-file"></i> File Hub</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'blog-home' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
              <!-- {{ request.get_host }}/blog/search/-->
          <form id="searchform" action="{% url 'search' %}" method="get">
            <input type="text" name="q" type="text" value="{{ request.GET.q }}" placeholder="Search Here..." />
            <button type="button" onclick="searchform.submit()" class=" text-white my-color btn-primary"><i class="fa fa-search"></i></button>
          </form>
          
          {% if user.is_authenticated %}
            <a href="{% url 'user-posts' user %}" class="btn text-white m-2" ><i class="fas fa-user-shield"></i> My Post</a>
            <a href="{% url 'post-create' %} " class="btn text-white m-2"><i class="fas fa-user-edit"></i> New Post</a>
            <a href="{% url 'profile' %} " class="btn text-white m-2"><i class="fas fa-user"></i> {{ user.username }}</a>
            <form method="POST" action="{% url 'logout' %}" class="d-inline">
              {% csrf_token %}
              <button type="submit" class="btn text-white m-2"><i class="fas fa-sign-out-alt"></i> Log Out</button>
            </form>
                
          {% else %}
            <a href="{% url 'login' %} " class="btn text-white m-2"><i class="fas fa-user-tie"></i> Log In</a>
            <a href="{% url 'register' %} " class="btn text-white m-2"> <i class="fas fa-sign-in-alt"></i> Sign Up</a>
          {% endif %}
              
          </div>
    </nav>

    <div class="container my-bg">
      {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
        {% endfor %}
      {% endif %}
      {% block content %}
        <div class="container d-flex flex-wrap justify-content-around" style="padding-top: 20px;">
          {% for post in posts %}
            <div class="card m-3 shadow-lg" style="width: 328px; max-width: 328px;">
              <div class="card-header d-flex align-items-center span">
                <a href="{{ post.author.profile.image.url }}" target="_blank">
                  <img src="{{ post.author.profile.image.url }}" alt="" class="rounded-circle img-thumbnail mr-3" style="width: 50px; height: 50px;">
                </a>
                <div>
                  <a class="text-dark" href="{% url 'user-posts' post.author.username %}">
                    <h5 class="mb-0">{{ post.author }}</h5>
                  </a>
                  <small class="text-muted">{{ post.date_upload|date:"F d, Y" }}</small>
                </div>
              </div>
              <div class="card-body">
                <h5 class="card-title">
                  <a class="text-dark" href="{% url 'post-detail' post.id %}">{{ post.title }}</a>
                  <p class="card-text">{{ post.content }}</p>
                </h5>
                <br>
                <div class="post-content">
                  {% if post.file %}
                    {% if post.extension in '.jpg.jpeg.png' %}
                      <a href="{{ post.file.url }}"  download ><img src="{{ post.file.url }}" alt="" class="img-fluid" style="max-width: 250px; height: 200px;padding-left: 20px;padding-top: 20px; padding-bottom: 20px;"></a>
                    {% elif post.extension == '.mp4' %}
                      <div>
                        <video id="video-1_html_api" class="vjs-tech" preload="auto" style="max-width: 250px; height: 200px;padding: 20px" >
                          <source src="{{ post.file.url }}" type="video/mp4" class="embed-responsive">
                        </video>
                      </div>
                      
                    {% else %}
                      <a href="{{ post.file.url }}"  download class="text-dark" style="max-width: 250px; height: 200px;padding:0px"><h5>{{ post.file }}</h5></a>
                    {% endif %}
                  {% endif %}
                </div>

              </div>
              <div class="post-download">
                <a href="{{ post.file.url }}" download class="btn btn-light btn-sm">
                  <i class="fas fa-download"></i> Download
                </a>
                
                
              </div>
            </div>
          {% endfor %}

        </div>
      {% endblock %}
    <div class="page-number">
      {% if is_paginated %}
        {% if page_obj.has_previous %}
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
            <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        {% endif %}

      {% endif %}
    </div>
    
    
    <!-- Script -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'blog/main.js' %}"></script>

 </body>
</html>

blog/templates/blog/post_confirm_delete.html
{% extends "blog/home.html" %}
{% block content %}
    <div class="container d-flex align-items-center justify-content-center" style="margin: 150px;">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h5>Are you sure you want to delete the post "{{ object.title }}"</h5>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends "blog/home.html" %}

{% block content %}
<div class="jumbotron shadow-lg mt-0 mb-0" style="height: 100%;">
  <article class="row">
    <div class="col-md-4 d-flex align-items-center justify-content-center author-image-container" style="background-color: #8d99ae;">
      <a href="{{ object.author.profile.image.url }}" target="_blank" class="author-image-link">
        <img src="{{ object.author.profile.image.url }}" alt="{{ object.author.username }}'s Profile Picture" class="author-image rounded-circle img-thumbnail img-fluid">
      </a>
    </div>
    
    <div class="col-md-7">
      <div class="meta-info">
        <div class="d-flex justify-content-between">
          <a class="mr-1 text-dark" href="{% url 'user-posts' object.author.username %}">
            <h4>{{ object.author }}</h4>
          </a>
          <small class="text-muted">{{ object.date_upload }}</small>
        </div>
        {% if object.author != user %}
        <div class="form-group d-flex ">          
          <a href="{{ object.file.url }}" download class="btn btn-secondary"><i class="fas fa-download"></i> Download</a>
        </div>
        {% endif %}
        <hr>
        {% if object.author == user %}
        <div class="edit-options">
          <a class="btn btn-secondary btn-sm" href="{% url 'post-update' object.id %}">Update</a>
          <a class="btn btn-danger btn-sm" href="{% url 'post-delete' object.id %}">Delete</a>
        </div>
        {% endif %}
      </div>
      <br>
      <div class="displaysection">
        {% if object.file %}
          {% if object.extension in '.jpg.jpeg.png' %}
            <a href="{{ object.file.url }}" download><img src="{{ object.file.url }}" alt="" class="img-fluid" style="max-width: 500px;max-height: 280px;"></a>
          {% elif object.extension == '.mp4' %}
            <div>
              <video controls style="max-width: 250px; height: 250px; max-height: 260px;" class="vjs-tech mt-2">
                <source src="{{ object.file.url }}" type="video/mp4" class="embed-responsive">
                Your browser does not support the video tag.
              </video>
            </div>
          {% else %}
          <div class="container">
            <a href="{{ object.file.url }}" style="margin: 125px;" download>{{ object.file }}</a>
          </div>
            
          {% endif %}
        {% endif %}
      </div>
      <h3>{{ object.title }}</h3>
      <p class="article-content">{{ object.content }}</p>
    </div>
  </article>
</div>
{% endblock content %}

<style>
  
  .displaysection {
    max-width: 100%;
    overflow: hidden;
    height: 600px;
  }
  .author-image-container {
    padding: 20px;
  }


  .author-image-link {
    display: block;
    text-align: center;
  }

  .author-image {
    width: 150px;
    height: 150px;
    object-fit: cover;
    border: 3px solid #fff;
    transition: all 0.3s ease;
  }

  .author-image:hover {
    transform: scale(1.1);
  }


</style>

blog/templates/blog/post_form.html
{% extends "blog/home.html" %}
{% block content %}
<div class="container">
    <div class="row justify-content-center" style="padding-top: 5px;">
        <div class="col-md-12">
            <div class="content-section">
                <form action="" method="POST" enctype="multipart/form-data" class="form-group">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4">Post</legend>
                        <div class="form-group">
                            <label for="id_title">Title:</label>
                            <input type="text" id="id_title" name="title" class="form-control {% if form.title.errors %}is-invalid{% endif %}">
                            {% if form.title.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.title.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="id_content">Content:</label>
                            <textarea id="id_content" name="content" class="form-control {% if form.content.errors %}is-invalid{% endif %}"></textarea>
                            {% if form.content.errors %}
                                <div class="invalid-feedback">
                                    {% for error in form.content.errors %}
                                        <p>{{ error }}</p>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                        <div class="form-group">
                            <label for="id_file">File:</label>
                            <input type="file" id="id_file" name="file" class="form-control-file">
                        </div>
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">
                            <i class="fas fa-upload"></i> Upload
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

blog/templates/blog/search.html
{% extends 'blog/home.html' %}
{% block content %}
<p>Posts containing '{{query_string}}'</p> 
<div class="row">
    {% for post in posts %}
    <div class="col-md-4 mb-4">
        <div>
            <span> {{ post.created }} </span>
            <a href="{% url 'post-detail' slug=post.slug %}"><h2 class="page-title">{{ post.title }}</h2></a>
            <div class="post">
                {{ post.body|safe }}
            </div>
        </div>
    </div>
    {% empty %}
    <div class="col">
        <p>No posts found.</p>
    </div>
    {% endfor %}
</div>

<div>
    {% if is_paginated %}
  
    {% if page_obj.has_previous %}
      <a class="btn btn-outline-info mb-4" href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ page_obj.previous_page_number }}">Previous</a>
    {% endif %}
  
    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
      {% endif %}
    {% endfor %}
  
    {% if page_obj.has_next %}
      <a class="btn btn-outline-info mb-4" href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}page={{ page_obj.next_page_number }}">Next</a>
    {% endif %}
  
  {% endif %}
</div>

{% endblock content %}

blog/templates/blog/user_posts.html
{% extends "blog/home.html" %}
{% block content %}
<div class="container d-flex flex-wrap justify-content-center" style="padding-top: 20px;">
  {% for post in posts %}
    <div class="card m-3 shadow-lg" style="width: 328px; max-width: 328px;">
      <div class="card-header d-flex align-items-center">
        <a href="{{ post.author.profile.image.url }}" target="_blank">
          <img src="{{ post.author.profile.image.url }}" alt="" class="rounded-circle img-thumbnail mr-3" style="width: 50px; height: 50px;">
        </a>
        <div>
          <a class="text-dark" href="{% url 'user-posts' post.author.username|urlencode %}">
            <h5 class="mb-0">{{ post.author }}</h5>
          </a>
          <small class="text-muted">{{ post.date_upload|date:"F d, Y" }}</small>
        </div>
      </div>
      <div class="card-body">
        <h5 class="card-title">
          <a class="text-dark" href="{% url 'post-detail' post.id %}">{{ post.title }}</a>
          <p class="card-text">{{ post.content }}</p>
        </h5>
        <br>
        <div class="post-content">
          {% if post.file %}
            {% if post.extension in '.jpg.jpeg.png' %}
              <a href="{{ post.file.url }}"  download ><img src="{{ post.file.url }}" alt="" class="img-fluid" style="max-width: 250px; height: 200px;padding:20px"></a>

            {% elif post.extension == '.mp4' %}
              <div>
                <video id="video-1_html_api" class="vjs-tech" preload="auto" style="max-width: 250px; height: 200px;padding: 20px;" >
                  <source src="{{ post.file.url }}" type="video/mp4" class="embed-responsive">
                </video>
              </div>
            {% else %}
              <a href="{{ post.file.url }}"  download class="text-dark" style="max-width: 250px; height: 200px;"><h5>{{ post.file }}</h5></a>
            {% endif %}
          {% endif %}
        </div>

      </div>
      <div class="post-download">
        <a href="{{ post.file.url }}" download class="btn btn-light btn-sm">
          <i class="fas fa-download"></i> Download
        </a>
        
      </div>
    </div>
  {% endfor %}

</div>
    
{% endblock content %}
<div>
  {% if is_paginated %}

  {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
  {% endif %}

  {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
      <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
      <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
  {% endif %}

{% endif %}
</div>

users/templates/users/login.html
{% load static %}
{% load crispy_forms_tags %}
<!-- login page -->
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->

    <meta charset="utf-8">
    <link rel="shortcut icon" href="{% static 'icon.png' %}" type="image/x-icon">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title>Login | FileHub</title>
</head>
<body>
  <div class="d-lg-flex half">
      <div class="bg order-1 order-md-3">
          <style>
              .bg {
                  background-image: url('{% static "images/bg_1.jpg" %}');
              }
          </style>
      </div>

      <div class="contents order-2 order-md-1">
        <div class="container">
          <div class="row align-items-center justify-content-center">
            <div class="col-md-7">
              <h3>Login to <strong>FileHub</strong></h3>
              <p class="mb-4">Unlock the Power of Seamless Sharing with FileHub</p>
              <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                  <legend class="border-bottom mb-4">Log In</legend>
                  <div class="form-group">
                    {{ form|crispy }}
                  </div>
            
                  <div class="d-flex mb-5 align-items-center">
                    <label class="control control--checkbox mb-0"><span class="caption">Remember me</span>
                      <input type="checkbox" checked="checked"/>
                      <div class="control__indicator"></div>
                    </label>
                    <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span>
                  </div>
                  <button class="btn btn-block btn-primary" type="submit">Login</button>
                </fieldset>
              </form>
              <div class="border-top pt-3">
                <small class="text-muted">
                  Need An Account? <a class="ml-2" href="{% url 'register' %}" style="color: blue;">Sign Up now</a>
                </small>
              </div>
            </div>
          </div>
        </div>
      </div> 
  </div>
  <!--scripts-->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

users/templates/users/logout.html
<!-- log out page-->
{% extends "blog/home.html" %}
{% block content %}
<div class="container d-flex align-items-center justify-content-center">
    <div class="text-center" style="margin: 250px;">
        <h3>You have been logged out</h3>
        <div class="border-top pt-2">
            <a href="{% url 'login' %}">Log In Again</a>
        </div>
    </div>
</div>
{% endblock content %}